### PR TITLE
P0 variants added

### PR DESCRIPTION
**Pull request by foolhardy21**
This PR has some additions to the variants of P0 components. Here is the list of those:

- Text Badge for Ecommerce Cards.
- Horizontal Card with Image height 100%. 
- Density Switching in Images.

Feel free to review. Thanks.

### CODE REVIEW

**Review by VLeads — APPROVED** [review]
Code looks good.

**Review by VLeads — APPROVED** [review]
Looks good

**Review by vrinda-mahajan — APPROVED** [review]
Good to merge.

**Review by anik31 — APPROVED** [review]
LGTM

**Pull request merged**
