### PR TITLE
List and Rating Component

### PR DESCRIPTION
**Pull request by foolhardy21**
This PR has:
- Simple list with icons.
- Stacked list with avatar for notifications.
- Rating Bar for E-commerce.

Feel free to review. Thanks.

### CODE REVIEW

**Review by anik31 — APPROVED** [review]
Nice work. Suggestion - Make cursor as pointer for rating component.

**Comment by foolhardy21** [comment]
> Nice work. Suggestion - Make cursor as pointer for rating component.

Thanks for reminding. Added the changes suggested.

**Review by vrx29 — APPROVED** [review]
Nice Work. color variables naming can be improved

**Comment by foolhardy21** [comment]
> Nice Work. color variables naming can be improved

I'll make the changes.

**Pull request merged**
