### PR TITLE
Image and Input components

### PR DESCRIPTION
**Pull request by foolhardy21**
- This PR has variants of image and input components. 
- For now ignore the button in inputs section because that respective branch is not merged yet. 
- Feel free to critique. Thanks.

### CODE REVIEW

**Comment by vrx29** [comment]
looks good to me just a suggestion try to use alt tag with img tag for better accessibility.

**Comment by anik31** [comment]
LGTM

**Comment by mikesch803** [comment]
everything looks good

**Comment by foolhardy21** [comment]
> looks good to me just a suggestion try to use alt tag with img tag for better accessibility.

Sure. Good point. ill make the changes

**Pull request merged**
